package main

import (
    "github.com/gin-gonic/gin"
    "github.com/swaggo/gin-swagger"
    "github.com/swaggo/files"
    _ "swagger/docs" // docs is generated by Swag CLI
)

// @title My API
// @version 1.0
// @description This is a sample API.
// @host localhost:8080
// @BasePath /api/v1
func main() {
    r := gin.Default()

    // Example endpoint
    // @Summary Get all users
    // @Description Returns a list of users
    // @Produce json
    // @Success 200 {array} string
    // @Router /users [get]
    r.GET("/users", func(c *gin.Context) {
        c.JSON(200, []string{"Alice", "Bob"})
    })

    // Swagger endpoint
    r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

    r.Run(":8080")
}